---
- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - config.yaml

  tasks:
    - name: Install Python3 and Pip3 for ubuntu
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-pip
      when: ansible_distribution == 'Ubuntu'

    - name: Install Python3 and Pip3 for centos
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-pip
      when: ansible_distribution == 'CentOS'  

    - name: Set Python3 as the default
      alternatives:
        name: python
        path: /usr/bin/python3

    - name: Install OpenJDK
      package:
        name: openjdk-11-jdk  
        state: present

    - name: Set Pip3 as the default pip
      alternatives:
        name: pip
        path: /usr/bin/pip3



